version: "3.8"

services:
  php:
    build: 
      context: ./php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html

  db:
      image: postgres
      environment:
        - POSTGRES_USER: postgres
        - POSTGRES_PASSWORD: lucas
        - POSTGRES_DB: teste
      ports:
        - '5432:5432'
      volumes:
        - ./dockerfile
    
